module.exports = function(pQueryname, pParams){
	var _SQLCommand = "";

	switch(pQueryname){
		case "SelectEhuftzMasterList":
			_SQLCommand += "SELECT IL_SEQ, \
								IL_NEWBAGNO, \
								IL_NEWSMALLNO, \
								IL_ORDERINDEX, \
								IL_BAGNO, \
 								IL_SMALLNO2, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_DECL_NO IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_DECL_NO ELSE EHUFTZ_MASTER_LIST2.EML_DECL_NO END AS EML_DECL_NO, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_DECL_TYPE IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_DECL_TYPE ELSE EHUFTZ_MASTER_LIST2.EML_DECL_TYPE END AS EML_DECL_TYPE, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_EXP_BAGNO IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_EXP_BAGNO ELSE EHUFTZ_MASTER_LIST2.EML_EXP_BAGNO END AS EML_EXP_BAGNO, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_HWB IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_HWB ELSE EHUFTZ_MASTER_LIST2.EML_HWB END AS EML_HWB, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_CLEARANCE_TYPE2 IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_CLEARANCE_TYPE2 ELSE EHUFTZ_MASTER_LIST2.EML_CLEARANCE_TYPE2 END AS EML_CLEARANCE_TYPE2, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_CLEARANCE_TYPE_STR IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_CLEARANCE_TYPE_STR ELSE EHUFTZ_MASTER_LIST2.EML_CLEARANCE_TYPE_STR END AS EML_CLEARANCE_TYPE_STR, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_PIECE IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_PIECE ELSE EHUFTZ_MASTER_LIST2.EML_PIECE END AS EML_PIECE, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_GCI_PIECE IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_GCI_PIECE ELSE EHUFTZ_MASTER_LIST2.EML_GCI_PIECE END AS EML_GCI_PIECE, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_GCO_PIECE IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_GCO_PIECE ELSE EHUFTZ_MASTER_LIST2.EML_GCO_PIECE END AS EML_GCO_PIECE, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_WEIGHT IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_WEIGHT ELSE EHUFTZ_MASTER_LIST2.EML_WEIGHT END AS EML_WEIGHT, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_GCI_WEIGHT IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_GCI_WEIGHT ELSE EHUFTZ_MASTER_LIST2.EML_GCI_WEIGHT END AS EML_GCI_WEIGHT, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_BAG_WEIGHT IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_BAG_WEIGHT ELSE EHUFTZ_MASTER_LIST2.EML_BAG_WEIGHT END AS EML_BAG_WEIGHT, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_FLIGHT_NO IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_FLIGHT_NO ELSE EHUFTZ_MASTER_LIST2.EML_FLIGHT_NO END AS EML_FLIGHT_NO, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_FLIGHT_DATE IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_FLIGHT_DATE ELSE EHUFTZ_MASTER_LIST2.EML_FLIGHT_DATE END AS EML_FLIGHT_DATE, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_GCI_DATE1 IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_GCI_DATE1 ELSE EHUFTZ_MASTER_LIST2.EML_GCI_DATE1 END AS EML_GCI_DATE1, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_GCO_DATE1 IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_GCO_DATE1 ELSE EHUFTZ_MASTER_LIST2.EML_GCO_DATE1 END AS EML_GCO_DATE1, \
								CASE WHEN EHUFTZ_MASTER_LIST1.EML_RELEASE_TIME IS NOT NULL THEN EHUFTZ_MASTER_LIST1.EML_RELEASE_TIME ELSE EHUFTZ_MASTER_LIST2.EML_RELEASE_TIME END AS EML_RELEASE_TIME, \
								CASE WHEN ROW_NUMBER() OVER(PARTITION BY IL_BAGNO ORDER BY IL_BAGNO) = 1 \
								THEN IL_BAGNO ELSE NULL END AS 'IL_BAGNO_NOREPEAT' \
							FROM ( \
								SELECT *, \
									REPLACE(IL_SMALLNO, '-', '') AS IL_SMALLNO2 \
								FROM ITEM_LIST \
								WHERE IL_SEQ = @EML_SEQ \
							) ITEM_LIST \
							LEFT JOIN ( \
								SELECT * \
								FROM PULL_GOODS \
								WHERE PG_SEQ = @EML_SEQ \
							) PULL_GOODS ON \
							IL_SEQ = PG_SEQ AND \
							IL_BAGNO = PG_BAGNO \
							LEFT JOIN ( \
								SELECT *, \
	 								( \
	 									SELECT SC_DESC \
	 									FROM SYS_CODE \
	 									WHERE SC_TYPE = 'ClearanceType' \
	 									AND SC_CODE = EML_CLEARANCE_TYPE \
	 									AND SC_STS = 0 \
	 								) AS EML_CLEARANCE_TYPE_STR, \
									CASE WHEN EML_CLEARANCE_TYPE = 'X' THEN '未見貨' ELSE EML_CLEARANCE_TYPE END AS EML_CLEARANCE_TYPE2 \
								FROM EHUFTZ_MASTER_LIST \
								WHERE EML_SEQ = @EML_SEQ \
							) EHUFTZ_MASTER_LIST1 ON EHUFTZ_MASTER_LIST1.EML_SEQ = IL_SEQ AND EHUFTZ_MASTER_LIST1.EML_HWB = IL_BAGNO \
							LEFT JOIN ( \
								SELECT *, \
	 								( \
	 									SELECT SC_DESC \
	 									FROM SYS_CODE \
	 									WHERE SC_TYPE = 'ClearanceType' \
	 									AND SC_CODE = EML_CLEARANCE_TYPE \
	 									AND SC_STS = 0 \
	 								) AS EML_CLEARANCE_TYPE_STR, \
									CASE WHEN EML_CLEARANCE_TYPE = 'X' THEN '未見貨' ELSE EML_CLEARANCE_TYPE END AS EML_CLEARANCE_TYPE2 \
								FROM EHUFTZ_MASTER_LIST \
								WHERE EML_SEQ = @EML_SEQ \
							) EHUFTZ_MASTER_LIST2 ON EHUFTZ_MASTER_LIST2.EML_SEQ = IL_SEQ AND EHUFTZ_MASTER_LIST2.EML_EXP_BAGNO = IL_BAGNO AND EHUFTZ_MASTER_LIST2.EML_HWB = IL_SMALLNO2 \
							WHERE /*沒被拉貨的*/ PG_SEQ IS NULL \
							ORDER BY IL_BAGNO ASC";
				
			break;
		case "SyncClearance":
			_SQLCommand += "SELECT IL_SEQ, \
								IL_NEWBAGNO, \
								IL_NEWSMALLNO, \
								IL_ORDERINDEX, \
								CASE WHEN ROW_NUMBER() OVER(PARTITION BY IL_BAGNO ORDER BY IL_BAGNO) = 1  \
								THEN IL_BAGNO ELSE NULL END AS 'IL_BAGNO_NOREPEAT', \
								IL_SMALLNO \
							FROM ( \
								SELECT * \
								FROM ITEM_LIST \
								WHERE IL_SEQ = @IL_SEQ \
							) ITEM_LIST \
							LEFT JOIN (  \
								SELECT *  \
								FROM PULL_GOODS  \
								WHERE PG_SEQ = @IL_SEQ  \
							) PULL_GOODS ON  \
							IL_SEQ = PG_SEQ AND  \
							IL_BAGNO = PG_BAGNO \
							WHERE /*沒被拉貨的*/ PG_SEQ IS NULL \
							ORDER BY IL_BAGNO ASC";
			break;
	}

	return _SQLCommand;
};